
POST  http://localhost:3003/api/blogs
content-type: application/json



{
   "title": "6 Blogi",
  "author": "Kaapo Kakko",
  "url": "Www.Jarintv.vom",
  "likes": "",
  "user" : "606f67f62d1cc9d17cd6df77"
}