
POST  http://localhost:3003/api/blogs
content-type: application/json



{
   "title": "Eka Blogi",
  "author": "Kaapo Kakko",
  "url": "Www.Jarintv.vom",
  "likes": "",
  "user" : "606d8801dab9279cde7c0363"
}