
POST  http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Jorman kalareissu Killen ja Jortsun kanssa3",
  "author": "Itse Jorma69",
  "url": "Www.Jromaliini.com/kalat",
  "likes": -3
}