POST  http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667/entries


 {
        "date" :"2077-05-01",
        "specialist": "Dr Rodriguez",
        "type": "HealthCheck",
        "description": "Weird mf imo atm nothing to do",
        "healthCheckRating": "2",
      }